### ISSUE TITLE
Wiring schematic  uncertainties/error

### ISSUE THREAD

**Issue by hartmanrik** [Lzhikai/SIBOOR-Voron-2.4-AUG#1]
I would strongly suggest to look at pages 11 and 12 in your Wiring Guide: [https://github.com/Lzhikai/SIBOOR-Voron-2.4-AUG/blob/main/Images/Octopus_Board_Wiring/SIBOOR%20V2.4%20AUG%20Wiring%20Schematic.pdf](url)

They both show different wiring of L and N! It's a small error to make with big consequences!

**Comment by notavisitor** [comment]
Thanks for the correction, it has been updated.
